
services:
  couchdb:
    image: couchdb:3.3.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=ai_trainer_admin
      - COUCHDB_PASSWORD=KTq29pZuEi1VsoNqf2mJMPTg
    volumes:
      - couchdb_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  couchdb_data: 