'use client';

import React from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Page } from '@/types';

interface LandingPageProps {
  onPageChange: (page: Page) => void;
}

export default function LandingPage({ onPageChange }: LandingPageProps) {
  const { user } = useAuth();

  const handleDemoLogin = async () => {
    // For now, we'll simulate a demo login
    // In the real implementation, you'd call the demo login endpoint
    console.log('Demo login clicked');
    // You can implement demo login logic here
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="max-w-7xl mx-auto px-4 py-12">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <div className="mb-8">
            <img 
              src="/formava_logo_med_v0_1.png" 
              alt="Formava AI Fitness" 
              className="h-24 w-auto mx-auto mb-6"
            />
          </div>
          
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            AI-Powered Personal Training
          </h1>
          
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Get personalized workout routines generated by AI, track your progress, 
            and achieve your fitness goals with intelligent recommendations tailored to your needs.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            {!user ? (
              <>
                <button
                  onClick={() => onPageChange('register')}
                  className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-700 transition-colors"
                >
                  Get Started
                </button>
                <button
                  onClick={() => onPageChange('login')}
                  className="bg-white text-blue-600 px-8 py-3 rounded-lg text-lg font-semibold border-2 border-blue-600 hover:bg-blue-50 transition-colors"
                >
                  Sign In
                </button>
              </>
            ) : (
              <button
                onClick={() => onPageChange('dashboard')}
                className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-700 transition-colors"
              >
                Go to Dashboard
              </button>
            )}
            
            <button
              onClick={handleDemoLogin}
              className="bg-gray-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-gray-700 transition-colors"
            >
              Try Demo
            </button>
          </div>
        </div>

        {/* Features Section */}
        <div className="grid md:grid-cols-3 gap-8 mb-16">
          <div className="bg-white p-6 rounded-lg shadow-md">
            <div className="text-blue-600 text-3xl mb-4">🤖</div>
            <h3 className="text-xl font-semibold mb-3">AI-Powered Routines</h3>
            <p className="text-gray-600">
              Get personalized workout routines generated by advanced AI, 
              considering your experience level, goals, and preferences.
            </p>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-md">
            <div className="text-blue-600 text-3xl mb-4">🏥</div>
            <h3 className="text-xl font-semibold mb-3">Injury-Aware Planning</h3>
            <p className="text-gray-600">
              Our AI considers your injuries and medical conditions to create 
              safe, effective workout plans that help you recover and progress.
            </p>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-md">
            <div className="text-blue-600 text-3xl mb-4">📱</div>
            <h3 className="text-xl font-semibold mb-3">Hevy Integration</h3>
            <p className="text-gray-600">
              Seamlessly sync your generated workouts with the Hevy app 
              for easy tracking and progress monitoring.
            </p>
          </div>
        </div>

        {/* How It Works Section */}
        <div className="bg-white rounded-lg shadow-md p-8">
          <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="bg-blue-100 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-blue-600 font-bold">1</span>
              </div>
              <h4 className="font-semibold mb-2">Create Profile</h4>
              <p className="text-gray-600 text-sm">
                Tell us about your fitness level, goals, and any injuries
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-blue-100 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-blue-600 font-bold">2</span>
              </div>
              <h4 className="font-semibold mb-2">AI Analysis</h4>
              <p className="text-gray-600 text-sm">
                Our AI analyzes your profile and workout history
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-blue-100 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-blue-600 font-bold">3</span>
              </div>
              <h4 className="font-semibold mb-2">Get Routines</h4>
              <p className="text-gray-600 text-sm">
                Receive personalized workout routines tailored to you
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-blue-100 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-blue-600 font-bold">4</span>
              </div>
              <h4 className="font-semibold mb-2">Track Progress</h4>
              <p className="text-gray-600 text-sm">
                Sync with Hevy and track your fitness journey
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

