import { Button } from '../ui/button';
import { Card, CardContent } from '../ui/card';
import { Badge } from '../ui/badge';
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '../ui/carousel';
import { ImageWithFallback } from '../figma/ImageWithFallback';
import { Dumbbell, Brain, Activity, Shield, Smartphone, Zap } from 'lucide-react';

interface LandingPageProps {
  onPageChange?: (page: 'login' | 'register') => void;
}

export function LandingPage({ onPageChange }: LandingPageProps) {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Workouts',
      description: 'Get personalized workout routines generated by advanced AI that adapts to your fitness level and goals.',
      image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXJzb25hbCUyMHRyYWluZXIlMjBleGVyY2lzZXxlbnwxfHx8fDE3NTg1ODA3MDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    },
    {
      icon: Activity,
      title: 'Hevy Integration',
      description: 'Seamlessly sync with Hevy workout tracking app for comprehensive fitness data management.',
      image: 'https://images.unsplash.com/photo-1580983703451-bf6bb44a9917?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHx8bW9iaWxlJTIwZml0bmVzcyUyMGFwcHxlbnwxfHx8fDE3NTg1ODA3MTR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    },
    {
      icon: Shield,
      title: 'Injury-Aware Planning',
      description: 'Smart workout planning that considers your injury history and physical limitations for safe training.',
      image: 'https://images.unsplash.com/photo-1593640852822-a44850096f9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXRuZXNzJTIwcHJvZ3Jlc3MlMjB0cmFja2luZ3xlbnwxfHx8fDE3NTg1ODA3MTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    },
    {
      icon: Smartphone,
      title: 'Mobile-First Design',
      description: 'Optimized for mobile use with responsive design that works perfectly on any device.',
      image: 'https://images.unsplash.com/photo-1580983703451-bf6bb44a9917?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHx8bW9iaWxlJTIwZml0bmVzcyUyMGFwcHxlbnwxfHx8fDE3NTg1ODA3MTR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    },
    {
      icon: Zap,
      title: 'Real-Time Sync',
      description: 'Keep your workout data synchronized across all platforms with real-time updates.',
      image: 'https://images.unsplash.com/photo-1669806954505-936e77929af6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXJkaW8lMjBydW5uaW5nJTIwdHJlYWRtaWxsfGVufDF8fHx8MTc1ODU1NzI3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    },
    {
      icon: Dumbbell,
      title: 'Comprehensive Tracking',
      description: 'Track your progress, set goals, and monitor your fitness journey with detailed analytics.',
      image: 'https://images.unsplash.com/photo-1591291621164-2c6367723315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlbmd0aCUyMHRyYWluaW5nJTIwd2VpZ2h0c3xlbnwxfHx8fDE3NTg1MjM2OTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
    }
  ];

  const heroImages = [
    {
      src: 'https://images.unsplash.com/photo-1756115484694-009466dbaa67?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXRuZXNzJTIwd29ya291dCUyMGd5bXxlbnwxfHx8fDE3NTg1MjA1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      alt: 'Modern gym with fitness equipment',
      title: 'State-of-the-art AI Training'
    },
    {
      src: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXJzb25hbCUyMHRyYWluZXIlMjBleGVyY2lzZXxlbnwxfHx8fDE3NTg1ODA3MDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      alt: 'Personal trainer helping with exercise form',
      title: 'Expert-guided Workouts'
    },
    {
      src: 'https://images.unsplash.com/photo-1591291621164-2c6367723315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlbmd0aCUyMHRyYWluaW5nJTIwd2VpZ2h0c3xlbnwxfHx8fDE3NTg1MjM2OTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
      alt: 'Strength training with weights',
      title: 'Strength & Power Building'
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-[--fitness-primary] to-[--fitness-secondary] text-white py-20 lg:py-32 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Hero Content */}
            <div className="text-center lg:text-left">
              <div className="flex items-center justify-center lg:justify-start gap-3 mb-6">
                <Dumbbell className="h-12 w-12" />
                <h1 className="text-4xl lg:text-6xl font-bold">Formava AI Trainer</h1>
              </div>
              <p className="text-xl lg:text-2xl mb-8 text-blue-100">
                Your intelligent workout companion that creates personalized training plans, 
                integrates with Hevy, and keeps you injury-free on your fitness journey.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Button 
                  size="lg" 
                  className="bg-[--fitness-accent] hover:bg-orange-600 text-white px-8 py-3 text-lg"
                >
                  Use Demo Account
                </Button>
                <Button 
                  variant="outline" 
                  size="lg"
                  className="border-white text-white hover:bg-white hover:text-[--fitness-primary] px-8 py-3 text-lg"
                >
                  Learn More
                </Button>
              </div>
            </div>

            {/* Hero Image Carousel */}
            <div className="relative">
              <Carousel className="w-full max-w-lg mx-auto">
                <CarouselContent>
                  {heroImages.map((image, index) => (
                    <CarouselItem key={index}>
                      <Card className="border-0 bg-white/10 backdrop-blur-sm">
                        <CardContent className="p-0">
                          <div className="relative aspect-[4/3] overflow-hidden rounded-lg">
                            <ImageWithFallback
                              src={image.src}
                              alt={image.alt}
                              className="w-full h-full object-cover"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                            <div className="absolute bottom-4 left-4 right-4">
                              <h3 className="text-white font-semibold text-lg">{image.title}</h3>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </CarouselItem>
                  ))}
                </CarouselContent>
                <CarouselPrevious className="left-2 bg-white/20 border-white/30 text-white hover:bg-white/40" />
                <CarouselNext className="right-2 bg-white/20 border-white/30 text-white hover:bg-white/40" />
              </Carousel>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">Features</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">
              Everything you need for smarter training
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Formava AI Trainer combines artificial intelligence with fitness expertise 
              to deliver personalized workout experiences that adapt to your unique needs.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <Card key={index} className="border-2 hover:border-[--fitness-primary] transition-colors overflow-hidden group">
                  <div className="relative h-48 overflow-hidden">
                    <ImageWithFallback
                      src={feature.image}
                      alt={feature.title}
                      className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
                    <div className="absolute top-4 left-4">
                      <div className="w-12 h-12 bg-[--fitness-primary] rounded-lg flex items-center justify-center">
                        <Icon className="h-6 w-6 text-white" />
                      </div>
                    </div>
                  </div>
                  <CardContent className="p-6">
                    <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Integration Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <Badge variant="secondary" className="mb-4">Integration</Badge>
              <h2 className="text-3xl lg:text-4xl font-bold mb-6">
                Works perfectly with Hevy
              </h2>
              <p className="text-lg text-muted-foreground mb-6">
                Formava AI Trainer integrates seamlessly with the Hevy workout tracking app, 
                allowing you to generate AI-powered routines and track them in your preferred platform.
              </p>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center gap-3">
                  <div className="w-2 h-2 bg-[--fitness-success] rounded-full"></div>
                  <span>Standalone use or Hevy integration</span>
                </li>
                <li className="flex items-center gap-3">
                  <div className="w-2 h-2 bg-[--fitness-success] rounded-full"></div>
                  <span>Sync workout history and progress</span>
                </li>
                <li className="flex items-center gap-3">
                  <div className="w-2 h-2 bg-[--fitness-success] rounded-full"></div>
                  <span>Export AI-generated routines directly</span>
                </li>
              </ul>
              <Button className="bg-[--fitness-primary] hover:bg-blue-700">
                Get Started Now
              </Button>
            </div>
            <div className="relative bg-gradient-to-br from-[--fitness-primary] to-[--fitness-secondary] p-8 rounded-2xl overflow-hidden">
              {/* Background Image */}
              <div className="absolute inset-0 opacity-20">
                <ImageWithFallback
                  src="https://images.unsplash.com/photo-1580983703451-bf6bb44a9917?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHx8bW9iaWxlJTIwZml0bmVzcyUyMGFwcHxlbnwxfHx8fDE3NTg1ODA3MTR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
                  alt="Mobile fitness app integration"
                  className="w-full h-full object-cover"
                />
              </div>
              
              <div className="relative bg-white rounded-xl p-6 shadow-lg">
                <div className="flex items-center gap-3 mb-4">
                  <Activity className="h-8 w-8 text-[--fitness-primary]" />
                  <div>
                    <h4 className="font-semibold">Hevy Integration</h4>
                    <p className="text-sm text-muted-foreground">Connected</p>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-sm">Workouts Synced</span>
                    <span className="text-sm font-medium">142</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm">Last Sync</span>
                    <span className="text-sm font-medium">2 min ago</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2">
                    <div className="bg-[--fitness-success] h-2 rounded-full w-4/5"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">Success Stories</Badge>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">
              Real results from real users
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              See how Formava AI Trainer has helped thousands achieve their fitness goals
            </p>
          </div>

          <Carousel className="w-full max-w-5xl mx-auto">
            <CarouselContent>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <Card className="h-full">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-12 h-12 rounded-full overflow-hidden">
                        <ImageWithFallback
                          src="https://images.unsplash.com/photo-1591050208162-34807da02a02?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYXBweSUyMGZpdG5lc3MlMjB3b21hbnxlbnwxfHx8fDE3NTg1ODA3OTd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
                          alt="Sarah's fitness success"
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h4 className="font-semibold">Sarah M.</h4>
                        <p className="text-sm text-muted-foreground">Lost 25 lbs in 3 months</p>
                      </div>
                    </div>
                    <p className="text-sm text-muted-foreground italic">
                      "The AI recommendations were spot-on for my knee injury. I finally found a program that works with my limitations, not against them."
                    </p>
                  </CardContent>
                </Card>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <Card className="h-full">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-12 h-12 rounded-full overflow-hidden">
                        <ImageWithFallback
                          src="https://images.unsplash.com/photo-1696393031102-a6598378e0aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhdGhsZXRpYyUyMG1hbiUyMHN1Y2Nlc3N8ZW58MXx8fHwxNzU4NTgwODAyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
                          alt="Marcus's fitness transformation"
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h4 className="font-semibold">Marcus T.</h4>
                        <p className="text-sm text-muted-foreground">Gained 15 lbs muscle</p>
                      </div>
                    </div>
                    <p className="text-sm text-muted-foreground italic">
                      "The Hevy integration is seamless. Having AI generate my routines and track them in Hevy has completely changed my training game."
                    </p>
                  </CardContent>
                </Card>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <Card className="h-full">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-12 h-12 rounded-full overflow-hidden">
                        <ImageWithFallback
                          src="https://images.unsplash.com/photo-1639496908117-6633c4aa9592?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXRuZXNzJTIwc3VjY2VzcyUyMHRyYW5zZm9ybWF0aW9ufGVufDF8fHx8MTc1ODU4MDc5NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
                          alt="Jessica's fitness journey"
                          className="w-full h-full object-cover"
                        />
                      </div>
                      <div>
                        <h4 className="font-semibold">Jessica L.</h4>
                        <p className="text-sm text-muted-foreground">PR'd all lifts</p>
                      </div>
                    </div>
                    <p className="text-sm text-muted-foreground italic">
                      "As a busy mom, the personalized 45-minute workouts fit perfectly into my schedule. The AI knows exactly what I need."
                    </p>
                  </CardContent>
                </Card>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <Card className="h-full">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-12 h-12 rounded-full bg-[--fitness-primary] flex items-center justify-center">
                        <Dumbbell className="h-6 w-6 text-white" />
                      </div>
                      <div>
                        <h4 className="font-semibold">David R.</h4>
                        <p className="text-sm text-muted-foreground">Injury-free for 8 months</p>
                      </div>
                    </div>
                    <p className="text-sm text-muted-foreground italic">
                      "After years of back problems, the injury-aware planning has kept me training consistently without setbacks."
                    </p>
                  </CardContent>
                </Card>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-[--fitness-primary] to-[--fitness-secondary] text-white">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl lg:text-4xl font-bold mb-6">
            Ready to transform your training?
          </h2>
          <p className="text-xl mb-8 text-blue-100">
            Join thousands of users who are already training smarter with AI-powered workouts.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg"
              className="bg-[--fitness-accent] hover:bg-orange-600 text-white px-8 py-3 text-lg"
              onClick={() => onPageChange?.('login')}
            >
              Try Demo Account
            </Button>
            <Button 
              variant="outline"
              size="lg"
              className="border-white text-white hover:bg-white hover:text-[--fitness-primary] px-8 py-3 text-lg"
              onClick={() => onPageChange?.('register')}
            >
              Create Account
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}